version: '3.8'
services:
  pokedex_api:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_ENV=development
    container_name: pokedex_api
    entrypoint: /app/builds/entrypoints/entrypoint-dev.sh
    environment:
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3000:3000
      - 9229:9229
      - 5555:5555
    volumes:
      - "./:/app"
    networks:
      - pokedex-network
      - api-gateway-network
      - backend-network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.4.2
    restart: always
    container_name: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=pokedex
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - backend-network
networks:
  api-gateway-network:
    name: apiGatewayNetwork
    external: true
  pokedex-network:
  backend-network:
volumes:
  db_volume:
