version: '3.5'
services:
  pokedex_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: pokedex_api
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - "/app/node_modules"
      - "./:/app"
    command: npm run start:debug
    networks:
      - pokedex-network
      - api-gateway-network
      - backend-network
    depends_on:
      - db
  db:
    image: mysql:8.4
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=pokedex
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - backend-network
networks:
  api-gateway-network:
    name: apiGatewayNetwork
    external: true
  pokedex-network:
  backend-network:
volumes:
  db_volume:
